[package]
name = "raft-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13.0"
prost = "0.13"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
rand = "0.9.0"

[build-dependencies]
tonic-build = "0.13.0"

